basePath: /api/v1
definitions:
  handler.APIResponse:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  handler.AdminUserResponse:
    properties:
      api_key:
        type: string
      created_at:
        type: string
      id:
        type: integer
      last_synced_at:
        type: string
      remark:
        type: string
      sharing_enabled:
        type: boolean
      updated_at:
        type: string
    type: object
  model.Cookie:
    properties:
      domain:
        type: string
      expires:
        description: Use pointer to handle null/zero time
        type: string
      http_only:
        type: boolean
      id:
        type: integer
      is_sharable:
        type: boolean
      last_updated_from_extension_at:
        type: string
      name:
        type: string
      path:
        type: string
      same_site:
        type: string
      secure:
        type: boolean
      user_id:
        type: integer
      value:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the API server for the Cookie Syncer browser extension.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Cookie Syncer API
  version: "1.0"
paths:
  /admin/users:
    post:
      consumes:
      - application/json
      description: Creates new users based on the request body array. Each object
        in the array can specify a remark.
      parameters:
      - description: Array of users to create. Can be empty to create one default
          user.
        in: body
        name: body
        required: true
        schema:
          items:
            properties:
              remark:
                type: string
            type: object
          type: array
      produces:
      - application/json
      responses:
        "201":
          description: Returns an array of created users including their new API keys.
          schema:
            allOf:
            - $ref: '#/definitions/handler.APIResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/handler.AdminUserResponse'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIResponse'
      security:
      - AdminKeyAuth: []
      summary: '[Admin] Create one or more users'
      tags:
      - Admin
  /admin/users/{id}:
    put:
      consumes:
      - application/json
      description: Updates a user's details, such as their remark.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User details to update
        in: body
        name: body
        required: true
        schema:
          properties:
            remark:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIResponse'
      security:
      - AdminKeyAuth: []
      summary: '[Admin] Update user by ID'
      tags:
      - Admin
  /admin/users/{id}/refresh-key:
    post:
      description: Generates a new API key for the specified user and returns the
        full updated user object.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/handler.AdminUserResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIResponse'
      security:
      - AdminKeyAuth: []
      summary: '[Admin] Refresh user API key by ID'
      tags:
      - Admin
  /admin/users/by-key/{apiKey}:
    put:
      consumes:
      - application/json
      description: Updates a user's details, such as their remark, by finding them
        via API key.
      parameters:
      - description: User API Key
        in: path
        name: apiKey
        required: true
        type: string
      - description: User details to update
        in: body
        name: body
        required: true
        schema:
          properties:
            remark:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIResponse'
      security:
      - AdminKeyAuth: []
      summary: '[Admin] Update user by API key'
      tags:
      - Admin
  /admin/users/by-key/{apiKey}/refresh-key:
    post:
      description: Generates a new API key for the specified user and returns the
        full updated user object.
      parameters:
      - description: User API Key
        in: path
        name: apiKey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/handler.AdminUserResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIResponse'
      security:
      - AdminKeyAuth: []
      summary: '[Admin] Refresh user API key by API key'
      tags:
      - Admin
  /auth/test:
    get:
      description: A simple endpoint to check if the provided API key in the `x-api-key`
        header is valid and associated with a user.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.APIResponse'
            - properties:
                data:
                  properties:
                    role:
                      type: string
                    user_id:
                      type: integer
                  type: object
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.APIResponse'
      security:
      - ApiKeyAuth: []
      summary: Test API Key
      tags:
      - Auth
  /cookies/{domain}:
    get:
      description: Retrieves cookies for a specific domain. By default, returns an
        HTTP header string. Use ?format=json to get structured JSON.
      parameters:
      - description: Domain
        in: path
        name: domain
        required: true
        type: string
      - description: Output format
        enum:
        - json
        in: query
        name: format
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.APIResponse'
            - properties:
                data:
                  type: object
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIResponse'
      security:
      - ApiKeyAuth: []
      summary: Get cookies for a domain
      tags:
      - Cookies
  /cookies/{domain}/{name}:
    get:
      description: Retrieves the raw value of a specific cookie, returned in the 'data'
        field.
      parameters:
      - description: Domain
        in: path
        name: domain
        required: true
        type: string
      - description: Cookie Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.APIResponse'
            - properties:
                data:
                  type: string
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIResponse'
      security:
      - ApiKeyAuth: []
      summary: Get a single cookie's value
      tags:
      - Cookies
  /cookies/all:
    get:
      description: Retrieves all cookies for the authenticated user. By default, groups
        them by domain and returns them as HTTP header strings. Use ?format=json to
        get structured JSON.
      parameters:
      - description: Output format
        enum:
        - json
        in: query
        name: format
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.APIResponse'
            - properties:
                data:
                  type: object
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIResponse'
      security:
      - ApiKeyAuth: []
      summary: Get all cookies
      tags:
      - Cookies
  /pool/cookies/{domain}:
    get:
      description: |-
        Retrieves all sharable cookies for a given domain from users who have opted into sharing.
        This endpoint is protected by a dedicated Pool Access Key (`x-pool-key` header), not a user's API key.
        By default, returns an array of strings, where each string is a user's cookies formatted as an HTTP 'Cookie' header.
        Use `?format=json` to get a structured JSON response, where each element contains the user's ID and their list of cookies.
      parameters:
      - description: The domain to fetch cookies for
        in: path
        name: domain
        required: true
        type: string
      - description: Output format
        enum:
        - json
        in: query
        name: format
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: JSON response with `?format=json`
          schema:
            allOf:
            - $ref: '#/definitions/handler.APIResponse'
            - properties:
                data:
                  items:
                    properties:
                      cookies:
                        type: object
                      user_id:
                        type: integer
                    type: object
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIResponse'
      security:
      - PoolKeyAuth: []
      summary: Get sharable cookies by domain
      tags:
      - Pool
  /sync:
    post:
      consumes:
      - application/json
      description: 'Receives a list of cookies from the browser extension. It then
        performs an atomic "replace" operation: all existing cookies for that user
        are deleted, and the new list is inserted. Finally, it returns the full updated
        list of cookies for the user.'
      parameters:
      - description: List of cookies to sync
        in: body
        name: cookies
        required: true
        schema:
          items:
            $ref: '#/definitions/model.Cookie'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.APIResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Cookie'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIResponse'
      security:
      - ApiKeyAuth: []
      summary: Sync cookies
      tags:
      - Sync
  /user/settings:
    get:
      description: Retrieves settings for the authenticated user, such as whether
        cookie sharing is enabled.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.APIResponse'
            - properties:
                data:
                  properties:
                    sharing_enabled:
                      type: boolean
                  type: object
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIResponse'
      security:
      - ApiKeyAuth: []
      summary: Get user settings
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Updates settings for the authenticated user, such as enabling or
        disabling cookie sharing.
      parameters:
      - description: Settings payload
        in: body
        name: body
        required: true
        schema:
          properties:
            sharing_enabled:
              type: boolean
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIResponse'
      security:
      - ApiKeyAuth: []
      summary: Update user settings
      tags:
      - User
securityDefinitions:
  AdminKeyAuth:
    in: header
    name: x-admin-key
    type: apiKey
  ApiKeyAuth:
    in: header
    name: x-api-key
    type: apiKey
  PoolKeyAuth:
    in: header
    name: x-pool-key
    type: apiKey
swagger: "2.0"
