# Top-level configuration
name = "cookie-syncer-api"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

# Bindings for D1, KV, etc.
[[d1_databases]]
binding = "DB" # This is the name of the binding in the worker code
database_name = "cookie-syncer-db"
database_id = "b0aede4f-b647-4174-821b-f6ede84addff" # This will be filled in by Wrangler after creation

# Environment variables for the worker
# Secrets like POOL_ACCESS_KEY and ADMIN_KEY should be set using `wrangler secret put <KEY_NAME>`.
# Plain text variables can be defined here if needed.
[vars]
# Example:
# MY_VAR = "my-value"
