# .air.toml
# Config for air, a live-reloading tool for Go applications.

# The root directory of our project
root = "."
# Temporary directory for builds
tmp_dir = "tmp"

[build]
# The main entry point of our application
cmd = "go build -o ./tmp/main.exe ./cmd/api/main.go"
# Binary file to run
bin = "tmp/main.exe"
# Command to run before building the binary.
# This is the correct way to ensure swagger docs are generated on every change.
pre_cmd = ["go run github.com/swaggo/swag/cmd/swag init -g cmd/api/main.go"]
# Directories to watch for changes
include_dir = ["cmd", "internal", "docs"]
# File extensions to watch
include_ext = ["go", "toml", "json"]
# Directories to ignore
exclude_dir = ["vendor"]
# Don't run the app on the first build
delay = 1000 # ms

[log]
# Show log time
time = true

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = true
