name: Release Browser Extension

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-extension:
    name: Build and Release Extension
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build browser extension
        run: npm run build

      - name: Package browser extension
        run: |
          cd dist
          zip -r ../cookiepusher-extension.zip .
          cd ..

      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cookiepusher-extension.zip
          generate_release_notes: true
          name: Extension Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
